FROM php:7.3-cli

# Install extensions and tools
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev unzip curl \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install gd mysqli pdo pdo_mysql \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy composer.json and composer.lock (ifexists) and install dependencies
COPY ./composer.json ./composer.lock /var/www/
# COPY ./composer.json ./composer.lock ./config/integration-tests-to-tester /var/www/
WORKDIR /var/www/
RUN composer config --no-plugins allow-plugins.composer/installers true && composer install

# Ensure that the directory has the propper rights
RUN chown -R www-data:www-data /var/www/
